/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.2.2).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.agenciadigital.api;

import io.swagger.annotations.*;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.context.request.NativeWebRequest;

import com.agenciadigital.service.domain.Empleado;

import javax.validation.Valid;

import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2020-10-31T09:17:10.375-05:00[America/Bogota]")

public interface IEmpleadoApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }


    public ResponseEntity<Void> empleadoDEL(@ApiParam(value = "Id del empleado",required=true) @PathVariable("idEmpleado") int idEmpleado);


    public List<Empleado> empleadosGETAll(@RequestParam(required = false, value = "fechaInicio") @DateTimeFormat(iso = ISO.DATE_TIME) LocalDateTime fechaInicio, @RequestParam(required = false, value = "fechaFin") @DateTimeFormat(iso = ISO.DATE_TIME) LocalDateTime fechaFin);


    public Empleado empleadoGETById(@ApiParam(value = "Id del empleado",required=true) @PathVariable("id") int id);



    public ResponseEntity<Empleado> empleadoPCT(@ApiParam(value = "Id del empleado", required = true) @PathVariable("id") int id,@ApiParam(value = "Empleado a actualizar"  )  @Valid @RequestBody Empleado empleado);

    public ResponseEntity<Empleado> empleadoPST(@ApiParam(value = "Empleado a registrar"  )  @Valid @RequestBody Empleado empleado);

}
